spring:
  application:
    name: api-gateway
  output:
    ansi:
      enabled: always

server:
  port: 5555
  use-forward-headers: true
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:11111/eureka
 
zuul:
  addHostHeader: true
  addProxyHeader: true
  routes:
    uaa:
      path: /uaa/**
      serviceId: movingdemoopenapi
      stripPrefix: false
      sensitiveHeaders: 

security:
  basic:
    enabled: false
  sessions: never
  oauth2:

    client:
      client-id: movingdemo-users
      client-secret: users-secret
      access-token-uri: http://localhost:8888/uaa/oauth/token
      user-authorization-uri: http://localhost:8888/uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:8888/uaa/me

Debug: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.netflix.zuul: Debug
    com.netflix.zuul: info
    com.shijin.learn: trace
    org.springframework.security.web.util: info
    

