debug: true

spring:
  application:
    name: api-gateway

server:
  port: 5555
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:11111/eureka
 
zuul:
  addHostHeader: true
  routes:
    uaa:
      path: /uaa/**
      serviceId: movingdemoopenapi
      stripPrefix: false
      sensitiveHeaders: 

logging:
  level:
    org.springframework.security: DEBUG